version: '2'
services:

  web:
    image: hitalos/laravel:latest
    ports:
        - 8080:80
    volumes:
        - ./:/var/www
    working_dir: /var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: homestead
        DB_USERNAME: username
        DB_PASSWORD: secret
        DB_CONNECTION: mysql
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
        # with mysql
        MYSQL_DATABASE: homestead
        MYSQL_USER: username
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
    ports:
        - "33061:3306"
volumes:
  dbdata:
